apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: jenkins2.gke.kearos.net
spec:
  secretName: tls-jenkins2-gke-kearos-net
  dnsNames:
  - jenkins2.gke.kearos.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - jenkins2.gke.kearos.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer