master:
  serviceType: ClusterIP
  healthProbes: false
  installPlugins:
    - blueocean:1.17.0
    - prometheus:2.0.0
    - kubernetes:1.17.2
  resources:
    requests:
      cpu: "1000m"
      memory: "1524Mi"
    limits:
      cpu: "2000m"
      memory: "3072Mi"
  javaOpts: "-XX:+AlwaysPreTouch -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions"
  ingress:
    enabled: true
    hostName: jenkins2.gke.kearos.net
    tls:
      - secretName: tls-jenkins2-gke-kearos-net
        hosts:
          - jenkins2.gke.kearos.net
    annotations:
      certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "false"
      nginx.ingress.kubernetes.io/proxy-body-size: 50m
      nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  podAnnotations:
    prometheus.io/path: /prometheus
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
agent:
  enabled: true
rbac:
  create: true

  # image: "cloudbees/cloudbees-jenkins-distribution"
  # imageTag: "2.176.1.4"
  # runAsUser: 1000
  # fsGroup: 1000

  # installPlugins:
  #   - kubernetes:1.16.0
  #   - workflow-job:2.32
  #   - workflow-aggregator:2.6
  #   - credentials-binding:1.19
  #   - git:3.10.0