apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: dui
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
      service: dui
  template:
    metadata:
      labels:
        type: backend
        service: dui
        language: go
    spec:
      containers:
      - name: api
        image: caladreas/buming
        livenessProbe:
          httpGet:
            path: /
            port: 7777
