apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: wolkje # or choose another name, must match deployment's env PROVISIONER_NAME'
---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: nfs-client-provisioner
    namespace: vasimos
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: nfs-client-provisioner
      spec:
        serviceAccountName: nfs-client-provisioner
        containers:
          - name: nfs-client-provisioner
            image: quay.io/external_storage/nfs-client-provisioner:latest
            volumeMounts:
              - name: nfs-client-root
                mountPath: /persistentvolumes
            env:
              - name: PROVISIONER_NAME
                value: wolkje
              - name: NFS_SERVER
                value: 192.168.178.42
              - name: NFS_PATH
                value: /nfs/kubernetes
        volumes:
          - name: nfs-client-root
            nfs:
              server: 192.168.178.42
              path: /nfs/kubernetes