apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: default
  labels:
    k8s-app: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: jenkins
    spec:
      containers:
        - name: master
          image: caladreas/jenkins-master-k8s
          ports:
            - name: http
              containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-service
  namespace: default
spec:
  selector:
    k8s-app: jenkins
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
