kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv-volum-01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/3"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv-volum-02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/4"