kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-claim
  labels:
    group: artifactory-k8s-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi