apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: artifactory-k8s-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: artifactory
        group: artifactory-k8s-demo

    spec:
      containers:
        - name: artifactory
          image: docker.bintray.io/jfrog/artifactory-oss:latest
          ports:
          - containerPort: 8081
          volumeMounts:
          - mountPath: "/var/opt/jfrog/artifactory"
            name: artifactory-volume
      volumes:
      - name: artifactory-volume
        persistentVolumeClaim:
          claimName: artifactory-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-claim
  labels:
    group: artifactory-k8s-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: artifactory
  labels:
    app: artifactory
    group: artifactory-k8s
spec:
  selector:
    app: artifactory
  ports:
  - name: http
    port: 80
    targetPort: 8081
    protocol: TCP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: artifactory
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/app-root: "/artifactory"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /artifactory
            backend:
              serviceName: artifactory
              servicePort: 80
      host: artifactory.127.0.0.1.nip.io