kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volum-01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volum-02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/2"